### ISSUE TITLE
The code of semi-supervised metric learning method

### ISSUE THREAD

**Issue by sudalvxin** [tjddus9597/STML-CVPR22#2]
Hi, thanks for this repository!

I was wondering if it would be possible to reproduce experiments of semi-supervised metric learning in your paper. As shown in Table 5,  semi-supervised metric learning outperforms supervised metric learning.

Thanks!

**Comment by sung-yeon-kim** [comment]
Since the authors of Slade[14] do not disclose the code, we were provided with the settings for the experiment from them.
For this reason, we apologize for not being able to publish the code.
